'use strict';

(function () {
  const PHOTOS_COUNT = 25;
  const HIDE_CLASS = 'hidden';

  const MAX_CONTROL_VALUE = 100;
  const MIN_CONTROL_VALUE = 25;
  const CONTROL_STEP = 25;
  const EFFECT_CLASS_START = 'effects__preview--';

  const HASHTAGS_MAX_COUNT = 5;
  const HASHTAGS_DELIMITER = ' ';
  const DESCRIPTION_MAX_LENGHT = 140;

  const DATA_LOAD_URL = "https://21.javascript.pages.academy/kekstagram/data";

  window.config = {
    PHOTOS_COUNT: PHOTOS_COUNT,
    HIDE_CLASS: HIDE_CLASS,
    MAX_CONTROL_VALUE: MAX_CONTROL_VALUE,
    MIN_CONTROL_VALUE: MIN_CONTROL_VALUE,
    CONTROL_STEP: CONTROL_STEP,
    EFFECT_CLASS_START: EFFECT_CLASS_START,
    HASHTAGS_MAX_COUNT: HASHTAGS_MAX_COUNT,
    HASHTAGS_DELIMITER: HASHTAGS_DELIMITER,
    DESCRIPTION_MAX_LENGHT: DESCRIPTION_MAX_LENGHT,
    DATA_LOAD_URL: DATA_LOAD_URL
  };
})();
